servername: test23234341232
#spring:
#  application:
#    name: springcloud-config
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/jilinwula/springcloud-config
#server:
#  port: 8081
userinfo:
  username: jilinwula
  password: 789afewrwer
